export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD'
export const REQUEST_FORGOT_PASSWORD_SUCCESS = 'REQUEST_FORGOT_PASSWORD_SUCCESS'
export const REQUEST_FORGOT_PASSWORD_FAIL = 'REQUEST_FORGOT_PASSWORD_FAIL'

export const UPDATE_PROGRESS_FORGOT = 'UPDATE_PROGRESS_FORGOT';
export const LOADING_FORGOT = 'LOADING_FORGOT';

export const REQUEST_FORGOT_SEND_MAIL = 'REQUEST_FORGOT_SEND_MAIL'
export const REQUEST_FORGOT_SEND_MAIL_SUCCESS = 'REQUEST_FORGOT_SEND_MAIL_SUCCESS'
export const REQUEST_FORGOT_SEND_MAIL_FAIL = 'REQUEST_FORGOT_SEND_MAIL_FAIL'

export const REQUEST_FORGOT_CHECK_CODE = 'REQUEST_FORGOT_CHECK_CODE'
export const REQUEST_FORGOT_UPDATE_PROGRESS = 'REQUEST_FORGOT_UPDATE_PROGRESS'
export const REQUEST_FORGOT_UPDATE_CODEID = 'REQUEST_FORGOT_UPDATE_CODEID'

export const REQUEST_FORGOT_CHANGE_PASSWORD = 'REQUEST_FORGOT_CHANGE_PASSWORD'
export const REQUEST_FORGOT_CHANGE_PASSWORD_SUCESS = 'REQUEST_FORGOT_CHANGE_PASSWORD_SUCESS'
export const REQUEST_FORGOT_CHANGE_PASSWORD_FAIL = 'REQUEST_FORGOT_CHANGE_PASSWORD_FAIL'




