export const LOGIN_PATH = "/dang-nhap";
export const SIGNUP_PATH = "/dang-ky";
export const FORGET_PASSWORD_PATH = "/quen-mat-khau";
export const FIND_TUTOR_PATH = "/tim-gia-su";
export const WAITING_CLASS_PATH = "/lop-cho-gia-su";
export const NEWS_PATH = "/tin-tuc";
export const HOME_PATH = "/";
export const TUTOR_LIST_PATH = "/danh-sach-gia-su";
export const FAQ_PATH = "/hoi-dap"; 
export const COURSE_PATH = "/khoa-hoc"; 
export const ME_PATH = "/tai-khoan"; 
export const PROFILE_PATH = "/ca-nhan"; 
export const COURSE_INFO_PATH = "/khoa-hoc"; 
export const CART_PATH = "/khoa-hoc-da-luu"; 
export const NOT_FOUND_PATH ="/4-0-4"