export const FILL_STEP_1 = 'FILL_STEP_1'
export const FILL_STEP_2 = 'FILL_STEP_2'
export const FILL_STEP_3 = 'FILL_STEP_3'
export const FIlL_ID = 'FILL_ID';
export const UPDATE_CODE_SIGNUP = 'UPDATE_CODE_SIGNUP';
export const UPDATE_PROGRESS_SIGNUP = 'UPDATE_PROGRESS_SIGNUP';
export const VALIDATE_CODE_SIGNUP = 'VALIDATE_CODE_SIGNUP';
export const LOADING_SIGNUP = 'LOADING_SIGNUP';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const REQUEST_SIGNUP_START = 'REQUEST_SIGNUP_START';
export const REQUEST_SIGNUP_SUCCESS = 'REQUEST_SIGNUP_SUCCESS';
export const REQUEST_SIGNUP_FAIL = 'REQUEST_SIGNUP_FAIL';

export const REQUEST_SIGNUP_SEND_MAIL = 'REQUEST_SIGNUP_SEND_MAIL';
export const REQUEST_SIGNUP_SEND_MAIL_SUCCESS = 'REQUEST_SIGNUP_SEND_MAIL_SUCCESS';
export const REQUEST_SIGNUP_SEND_MAIL_FAIL = 'REQUEST_SIGNUP_SEND_MAIL_FAIL';

export const REQUEST_SIGNUP_CHECK_CODE = 'REQUEST_SIGNUP_CHECK_CODE';
export const REQUEST_SIGNUP_CHECK_CODE_SUCCESS = 'REQUEST_SIGNUP_CHECK_CODE_SUCCESS';
export const REQUEST_SIGNUP_CHECK_CODE_FAIL = 'REQUEST_SIGNUP_CHECK_CODE_FAIL';

export const REQUEST_SIGNUP_PROFILE = 'REQUEST_SIGNUP_PROFILE';
export const REQUEST_SIGNUP_PROFILE_SUCCESS = 'REQUEST_SIGNUP_PROFILE_SUCCESS';
export const REQUEST_SIGNUP_PROFILE_FAIL = 'REQUEST_SIGNUP_PROFILE_FAIL';






